# Generated by Django 6.1 on 2026-09-12 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='orders.diningsession'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.bill'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_items', to='orders.orderitem'),
        ),
    ]
