# Generated by Django 6.1 on 2026-09-19 11:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_id', models.IntegerField()),
                ('quantity_required', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_links', to='inventory.ingredient')),
            ],
            options={
                'unique_together': {('menu_item_id', 'ingredient')},
            },
        ),
    ]
